module.exports = async () => {
  return [
    {
      createdOn: Date.now(),
      editedOn: Date.now(),
      project: "5f3ea32b1d4e36363c2b9813",
      plotID: 1,
      act: "1",
      scene: "1",
      data: "This is scene 1",
      charachters: [],
    },
    {
      createdOn: Date.now(),
      editedOn: Date.now(),
      project: "5f3ea32b1d4e36363c2b9813",
      plotID: 2,
      act: "1",
      scene: "2",
      data: "This is scene 2",
      charachters: [],
    },
    {
      createdOn: Date.now(),
      editedOn: Date.now(),
      project: "5f3ea32b1d4e36363c2b9813",
      plotID: 3,
      act: "1",
      scene: "3",
      data: "This is scene 3",
      charachters: [],
    },
    {
      createdOn: Date.now(),
      editedOn: Date.now(),
      project: "5f3ea32b1d4e36363c2b9813",
      plotID: 4,
      act: "2",
      scene: "1",
      data: "We are starting on Act 2",
      charachters: [],
    },
    {
      createdOn: Date.now(),
      editedOn: Date.now(),
      project: "5f3ea32b1d4e36363c2b9813",
      plotID: 5,
      act: "2",
      scene: "2",
      data: "We are still on Act 2. This one is a little longer",
      charachters: [],
    },
    {
      createdOn: Date.now(),
      editedOn: Date.now(),
      project: "5f3ea32b1d4e36363c2b9813",
      plotID: 6,
      act: "3",
      scene: "1",
      data: "We are still on Act 3. This one is a little longer",
      charachters: [],
    },
    {
      createdOn: Date.now(),
      editedOn: Date.now(),
      project: "5f3ea32b1d4e36363c2b9813",
      plotID: 7,
      act: "3",
      scene: "2",
      data: "We are still on Act 3. Scene 2",
      charachters: [],
    },
    {
      createdOn: Date.now(),
      editedOn: Date.now(),
      project: "5f3ea32b1d4e36363c2b9813",
      plot: 8,
      act: "3",
      scene: "3",
      data: "We are still on Act 3. Scene 2",
      charachters: [],
    },
    {
      createdOn: Date.now(),
      editedOn: Date.now(),
      project: "5f3ea32b1d4e36363c2b9813",
      plotID: 9,
      act: "3",
      scene: "4",
      data: "We are still on Act 3. Scene 2",
      charachters: [],
    },

  ];
}